repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5  # Use the latest version
    hooks:
      - id: clang-format
      # Add a hook for clang-tidy here if available

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: ./scripts/run-clang-tidy.sh
        language: system
        files: \.(cpp|hpp|cc|h|cxx)$

  - repo: local
    hooks:
      - id: cmake-format
        name: cmake-format
        entry: cmake-format
        language: system
        files: CMakeLists\.txt|\.cmake$
        types: [file]
        # Define the cmake-format version in additional_dependencies if needed

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2  # Use the latest version
    hooks:
      - id: flake8
