name: Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clang-tidy
      run: sudo apt-get install -y clang-tidy

    - name: Run clang-tidy
      run: |
        find src -regex '.*\.\(cpp\|cc\|cxx\)' | while read -r file; do
          clang-tidy "$file" -- -Iinclude
        done
